apiVersion: apps/v1
kind: Deployment
metadata:
  name: better-app-deployment
  namespace: better-app-dev
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: better-app
  template:
    metadata:
      labels:
        app: better-app
    spec:
      containers:
      - name: better-app
        image: ghcr.io/jaylikhare316/better_app:dev-6c1470f6c54fccc89a4deef5919c7dc63a2cb0af
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "development"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
