apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: better-app-dev
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "YOUR_BASE64_ENCODED_GITHUB_TOKEN"
        }
      }
    }
