apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: better-app-dev
  namespace: better-app-dev
  labels:
    app: better-app
    environment: dev
spec:
  serviceName: better-app-dev-headless
  replicas: 1
  selector:
    matchLabels:
      app: better-app
      environment: dev
  template:
    metadata:
      labels:
        app: better-app
        environment: dev
    spec:
      containers:
      - name: better-app
        image: better-app:latest
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: FLASK_ENV
          value: "development"
        - name: FLASK_DEBUG
          value: "1"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: DB_PATH
          value: "/data/names.db"
        volumeMounts:
        - name: database-storage
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
  volumeClaimTemplates:
  - metadata:
      name: database-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
