apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: better-app-statefulset
  namespace: better-app-dev
spec:
  serviceName: better-app-headless
  replicas: 2
  selector:
    matchLabels:
      app: better-app
  template:
    metadata:
      labels:
        app: better-app
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: better-app
        image: ghcr.io/jaylikhare316/better_app:dev-e2584b08366c71e0599b1e171f5b817b098581f5
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: DB_PATH
          value: "/data/names.db"
        - name: LOG_LEVEL
          value: "DEBUG"
        volumeMounts:
        - name: data
          mountPath: /data
        startupProbe:
          httpGet:
            path: /health
            port: 5000
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
