apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: better-app-statefulset
  namespace: better-app-dev
spec:
  serviceName: better-app-headless
  replicas: 2
  selector:
    matchLabels:
      app: better-app
  template:
    metadata:
      labels:
        app: better-app
    spec:
      containers:
      - name: better-app
        image: ghcr.io/jaylikhare316/better_app:dev-24fe41412964130d82ddc80f488a4efe31bfea24
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "development"
        - name: DB_PATH
          value: "/data/names.db"
        volumeMounts:
        - name: data
          mountPath: /data
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
