apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: better-app-statefulset
  namespace: better-app-dev
spec:
  serviceName: better-app-headless
  replicas: 2
  selector:
    matchLabels:
      app: better-app
  template:
    metadata:
      labels:
        app: better-app
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: better-app
        image: ghcr.io/jaylikhare316/better_app:dev-f263d3ae3c7e9080c665dcab7473606b5726f2a0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: DB_PATH
          value: "/data/names.db"
        - name: LOG_LEVEL
          value: "DEBUG"
        volumeMounts:
        - name: data
          mountPath: /data
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
