name: Simple CI/CD Pipeline

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: write
  packages: write
  
jobs:
  # STAGE 1: Build and push Docker image
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    outputs:
      sha: ${{ github.sha }}
      image_tag: ${{ steps.image_tag.outputs.tag }}
      image_name_lower: ${{ steps.lowercase.outputs.image_name_lower }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set lowercase image name
      id: lowercase
      run: |
        echo "image_name_lower=$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Generate image tag
      id: image_tag
      run: |
        echo "tag=${{ env.REGISTRY }}/${{ steps.lowercase.outputs.image_name_lower }}:dev-${{ github.sha }}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.image_tag.outputs.tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # STAGE 2: Security scan with Trivy
  scan:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
    - name: Run Trivy container scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ needs.build.outputs.image_tag }}
        format: 'table'
        severity: 'CRITICAL'
        exit-code: '1'
        ignore-unfixed: true

  # STAGE 3: Deploy to Kubernetes via ArgoCD
  deploy:
    needs: [build, scan]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Update Kubernetes manifests
      run: |
        sed -i "s|image: .*|image: ${{ needs.build.outputs.image_tag }}|" k8s/statefulset.yaml
        sed -i "s|image: .*|image: ${{ needs.build.outputs.image_tag }}|" k8s/deployment.yaml
        echo "Updated image to: ${{ needs.build.outputs.image_tag }}"
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add k8s/statefulset.yaml k8s/deployment.yaml
        git commit -m "Deploy: dev-${{ needs.build.outputs.sha }}" || exit 0
        git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
        echo "Deployment ready for ArgoCD sync"