name: Simple Pipeline

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PYTHON_VERSION: "3.11"

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      
      - name: Run tests
        run: |
          pytest --cov=./ --cov-report=xml
      
      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Extract branch or tag name
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          TAG_NAME=${GITHUB_REF#refs/tags/}
          
          # Set image tag based on branch/tag
          if [[ "$BRANCH_NAME" == "master" ]]; then
            IMAGE_TAG="latest"
          elif [[ "$BRANCH_NAME" == "develop" ]]; then
            IMAGE_TAG="dev-latest"
          else
            IMAGE_TAG=${TAG_NAME}
          fi
          
          # Build and push
          docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
      
      - name: Deploy to Kubernetes
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
        run: |
          echo "Deploying to Kubernetes via ArgoCD..."
          # In a real scenario, you might trigger ArgoCD sync or update a kustomize overlay
          # For this simplified pipeline, we'll just echo the deployment step
          echo "Deployment would happen here through ArgoCD auto-sync"
